# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ShareDB
baseurl: "/sharedb" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

aux_links:
  "ShareDB on GitHub":
    - "//github.com/share/sharedb"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/share/sharedb" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
permalink: /:path/:name

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Global copy
copy:
  events: This class extends [`EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter), and can be used with the normal methods such as [`on()`](https://nodejs.org/api/events.html#events_emitter_on_eventname_listener) and [`off()`](https://nodejs.org/api/events.html#events_emitter_off_eventname_listener).
